# Generated by Django 5.2.15 on 2026-07-01 12:03

import django.core.serializers.json
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extras', '0142_remove_scheduledjob_approval_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='VLANRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('_custom_field_data', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('vlan_id', models.PositiveIntegerField(unique=True)),
                ('vlan_name', models.CharField(max_length=100)),
                ('tenant', models.CharField(max_length=100)),
                ('subnet', models.CharField(max_length=50)),
                ('gateway', models.GenericIPAddressField()),
                ('tags', nautobot.core.models.fields.TagsField(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'abstract': False,
            },
            bases=(nautobot.extras.models.mixins.DataComplianceModelMixin, nautobot.extras.models.mixins.DynamicGroupMixin, nautobot.extras.models.mixins.NotesMixin, models.Model),
        ),
    ]
