# Generated by Django 5.2.15 on 2026-07-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_vlan_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vlanrequest',
            options={'ordering': ['vlan_id']},
        ),
        migrations.AddField(
            model_name='vlanrequest',
            name='rendered_yaml',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vlanrequest',
            name='status',
            field=models.CharField(default='Requested', max_length=20),
        ),
    ]
