# Generated by Django 5.2.15 on 2026-07-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_vlan_request', '0002_alter_vlanrequest_options_vlanrequest_rendered_yaml_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlanrequest',
            name='vrf',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
