# Generated by Django 5.2.15 on 2026-07-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_vlan_request', '0003_vlanrequest_vrf'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlanrequest',
            name='git_branch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='vlanrequest',
            name='git_commit',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
